services:
  app:
    command: make dev
    build:
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.7.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
